### ISSUE TITLE
Create new account : update the highlighted text 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#10]
Current : Please complete the fields below. All fields are required
![image](https://user-images.githubusercontent.com/17116943/31925676-efa92e12-b8a7-11e7-9527-75c54a0ef222.png)

Expected : Please fill all the required fields below

**Comment by SumithraKB** [comment]
Works
![image](https://user-images.githubusercontent.com/26400070/32048605-af66e8f0-ba67-11e7-8358-4eb6a59126b8.png)
