### ISSUE TITLE
List of accounts : Styling of the processing message 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#11]
http://stage.projectx.com/website

current : 
![image](https://user-images.githubusercontent.com/17116943/31925778-8ff03910-b8a8-11e7-87a1-3a75005af6ac.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/32049801-129a2370-ba6c-11e7-964f-2e7420a7c631.png)
