### ISSUE TITLE
Voucher code pop up, input box alignment

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#111]
http://cloudpath.ajency.in/benefits/

current : 
![image](https://user-images.githubusercontent.com/17116943/33305401-fdb8bf7a-d433-11e7-8026-17c4a11fc8c5.png)

**Comment by SumithraKB** [comment]
Works now 
![image](https://user-images.githubusercontent.com/26400070/33700975-5f4dd940-db42-11e7-9c8a-f8f04c6baf4d.png)
