### ISSUE TITLE
Voucher code pop up is displayed only 3 times though total added is 5

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#113]
http://cloudpath.ajency.in/contact-us/

configuration selected as follows : 
![image](https://user-images.githubusercontent.com/17116943/33306030-b556e4e8-d436-11e7-9a95-fb32c4a2d9d2.png)

![image](https://user-images.githubusercontent.com/17116943/33306046-c407ac84-d436-11e7-94ef-53a73841e446.png)

Current : voucher code pop up is displayed only 3 times on the site though total is selected as 5 times
![image](https://user-images.githubusercontent.com/17116943/33306071-e6491832-d436-11e7-98cd-07ef04a28870.png)

**Comment by cinthiavernekar** [comment]
Issue also in case of following config : 
![image](https://user-images.githubusercontent.com/17116943/33309275-8eddcdba-d443-11e7-8f79-dc084c115cde.png)
![image](https://user-images.githubusercontent.com/17116943/33309293-a20716f8-d443-11e7-9147-cb35d1a1fa60.png)

**Comment by cinthiavernekar** [comment]
issue on mobile as well

**Comment by cinthiavernekar** [comment]
issue also for direct booking tool

**Comment by SumithraKB** [comment]
Works now for direct booking and voucher code tools
