### ISSUE TITLE
Room rates and number of rooms accept negative values 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#12]
http://stage.projectx.com/website/5

current : 
![image](https://user-images.githubusercontent.com/17116943/31927421-8fc9b4b2-b8b1-11e7-82c8-18b16a0aa8ad.png)

**Comment by SumithraKB** [comment]
Error messages are wrong
![image](https://user-images.githubusercontent.com/26400070/32046553-0a4e082c-ba61-11e7-9a85-755ec712281b.png)

keep it like "This value should be greater than zero.
