### ISSUE TITLE
Voucher tool display issue

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#125]
http://cloudpath.ajency.in/team/

config selected : 
![image](https://user-images.githubusercontent.com/17116943/33369969-25b9913c-d51c-11e7-9e95-cebb82530da7.png)
![image](https://user-images.githubusercontent.com/17116943/33369990-3203b8dc-d51c-11e7-9a1d-daf2baf506f6.png)

Current : voucher code tool is displayed on team page
![image](https://user-images.githubusercontent.com/17116943/33370051-64197ef6-d51c-11e7-9bbf-ede788dd4b9e.png)

Expected : As per the config selected, voucher tool shouldn't be displayed on team page

**Comment by cinthiavernekar** [comment]
Issue also in following config
![image](https://user-images.githubusercontent.com/17116943/33370621-240ad0ba-d51e-11e7-972b-2cb7d35f9922.png)
![image](https://user-images.githubusercontent.com/17116943/33370648-365bcaa8-d51e-11e7-8b29-b1a5a2b13eec.png)

**Comment by cinthiavernekar** [comment]
Issue on mobile ( android + iOS )

**Comment by SumithraKB** [comment]
@prajay04 This is not working yet. Also show on specific pages also does not work.

**Comment by SumithraKB** [comment]
For mobile, for the below settings

![image](https://user-images.githubusercontent.com/26400070/33761836-7869399e-dc30-11e7-83b9-64f37f528664.png)

the "plus" button is shown on "team" page. If the configuration is set not show on particular pages, then it should not show the plus icon as well.

similarly for "specific pages" configuration.

**Comment by cinthiavernekar** [comment]
@prajay04 for the above config if mobile state is selected as closed then the "plus" button is not displayed on any of the pages.

**Comment by cinthiavernekar** [comment]
issue fixed.
