### ISSUE TITLE
List of Accounts : sorting should be based upon the created on date

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#13]
http://stage.projectx.com/website

current : created by in ascending order 

Expected : sorting of the data should be based upon the created on date in ascending order with sorting options

**Comment by SumithraKB** [comment]
Latest entry should be shown first by default 
(descending order of date)
![image](https://user-images.githubusercontent.com/26400070/32046782-98f568a4-ba61-11e7-87e0-15de4228a3b2.png)
