### ISSUE TITLE
voucher code not displayed on mobile on click of the "add" icon

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#133]
http://cloudpath.ajency.in/benefits/

voucher booking configuration is selected as close for mobile
![image](https://user-images.githubusercontent.com/17116943/33427660-199fc62a-d5ec-11e7-87bf-bca35dac791e.png)
![image](https://user-images.githubusercontent.com/17116943/33427688-2c6bd942-d5ec-11e7-9f8f-6c26e7030fa3.png)

current : voucher code pop up dsnt open up on click of the add icon
![image](https://user-images.githubusercontent.com/17116943/33427787-85fbc5e4-d5ec-11e7-9a44-97b586133245.png)

**Comment by SumithraKB** [comment]
Works now
