### ISSUE TITLE
List of Accounts : Add help text in the search box " Search by Name or Domain Name "

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#14]
http://stage.projectx.com/website

current : 
![image](https://user-images.githubusercontent.com/17116943/31928670-9e3359fe-b8b6-11e7-883d-21a1e2d12b00.png)

Expected : Add help text in the search box and also **ADD SPACE BETWEEN SEARCH LABEL AND BOX**
![image](https://user-images.githubusercontent.com/17116943/31928713-c6dc29ee-b8b6-11e7-8283-5f99c15430d5.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/32049891-7651ebaa-ba6c-11e7-8dd1-c7c0b45dd921.png)
