### ISSUE TITLE
On click of close button on any message, the messages goes down abruptly

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#155]
Initially 

![image](https://user-images.githubusercontent.com/26400070/33554010-08dd15e4-d921-11e7-97de-bc1a1eb3d273.png)

After clicking on close of one messages, remaining messages moved down abruptly
![image](https://user-images.githubusercontent.com/26400070/33554016-1206cb4c-d921-11e7-80b9-977a33aadfda.png)

**Comment by cinthiavernekar** [comment]
works now
