### ISSUE TITLE
List of Accounts : Change the text "Edit" to "Edit Account"

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#16]
http://stage.projectx.com/website

current : 
![image](https://user-images.githubusercontent.com/17116943/31931242-2ee8732c-b8c0-11e7-8cd7-d00998e8060e.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/32049600-3d6a1638-ba6b-11e7-8708-3e4bf93edd77.png)
