### ISSUE TITLE
show on entire website/show on specific pages configuration not working for instant discount tool 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#163]
http://cloudpath.ajency.in/faq/

current : instant booking tool displayed on all the pages though specific page is selected
![image](https://user-images.githubusercontent.com/17116943/33593445-7b6099bc-d9b5-11e7-8b44-b1c1a1922f1d.png)

**Comment by SumithraKB** [comment]
@prajay04 : not working

**Comment by SumithraKB** [comment]
Works now.

**Comment by SumithraKB** [comment]
Works
