### ISSUE TITLE
Click on add more does not show the color pickers sometimes

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#169]
![image](https://user-images.githubusercontent.com/26400070/33598737-d363aa6e-d9c9-11e7-83f0-b6fd777e4b76.png)

**Comment by SumithraKB** [comment]
@tanvisalkar  : Still the same 
![image](https://user-images.githubusercontent.com/26400070/33650883-ccddf580-da89-11e7-963b-4f77debdbc1d.png)

**Comment by SumithraKB** [comment]
Not working

**Comment by tanvisalkar** [comment]
please add the steps to follow to reach this case unable to replicate the issue

**Comment by SumithraKB** [comment]
Unable to replicate this issue now.
