### ISSUE TITLE
List of Accounts : Archived accounts shouldn't be displayed by default 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#17]
http://stage.projectx.com/website

current : Archived accounts are displayed by default when the page loads 
![image](https://user-images.githubusercontent.com/17116943/31931368-a3ed1ed4-b8c0-11e7-9146-411d70bfca76.png)

Expected : **Archived accounts shouldn't be displayed by default, should be visible only when the status filter is applied**

**Comment by SumithraKB** [comment]
Ok. this works fine. Archived records can be seen only on filtering specifically for it.
