### ISSUE TITLE
Voucher code is not displayed ,variable name is displayed in the tool and email

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#172]
Configuration : 
![image](https://user-images.githubusercontent.com/26400070/33600111-4c6e8ac4-d9ce-11e7-93e3-997515ee1807.png)

Tool display : 
![image](https://user-images.githubusercontent.com/26400070/33600055-26af6628-d9ce-11e7-9379-781db72633a5.png)

email : 
![image](https://user-images.githubusercontent.com/26400070/33600454-49c9887c-d9cf-11e7-9967-4e1b8402b23f.png)

**Comment by cinthiavernekar** [comment]
works now
