### ISSUE TITLE
OTP issue when voucher code and instant discount popup is submitted simultaneously

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#173]
Current : when voucher code and instant discount popup is submitted simultaneously, two different otp are sent which will be difficult for the user to understand which code to use where.

Expectd : In such scenarios otp sent should be same for both the codes.

**Comment by SumithraKB** [comment]
Different OTPS are generated for both

**Comment by SumithraKB** [comment]
Works now
