### ISSUE TITLE
List of accounts : add space between colan and search box

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#19]
http://staging.obodos.com/website

current : 
![image](https://user-images.githubusercontent.com/17116943/32091329-449b86e8-bb11-11e7-8af0-e8474a9c2aee.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/33480258-8681f09a-d6b6-11e7-8999-6c6371382aa9.png)
