### ISSUE TITLE
Mobile pop up alignment changes with desktop alignment settings :

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#42]
Mobile pop up alignment changes with desktop alignment settings : 
1.
![image](https://user-images.githubusercontent.com/26400070/32313625-e18f088c-bfc9-11e7-80e3-ba8c1d3618bd.png)

![image](https://user-images.githubusercontent.com/26400070/32313617-d8910ffa-bfc9-11e7-87b0-c4ad18ac1948.png)

2. 
![image](https://user-images.githubusercontent.com/26400070/32313644-f75820cc-bfc9-11e7-9665-3cc8b0ce6f32.png)
![image](https://user-images.githubusercontent.com/26400070/32313656-017715ae-bfca-11e7-96ef-b43ac3213dbf.png)

3.
![image](https://user-images.githubusercontent.com/26400070/32313676-1c42b9e2-bfca-11e7-883c-6ac6450b3d9d.png)

![image](https://user-images.githubusercontent.com/26400070/32313666-1380279a-bfca-11e7-8af4-fb40a6a8b004.png)

**Comment by jeromie** [comment]
@tanvisalkar  this will be fixed once the mobile specific generic css file is loaded on mobile

**Comment by SumithraKB** [comment]
Works
