### ISSUE TITLE
Get code | email content

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#52]
![image](https://user-images.githubusercontent.com/26400070/32428285-fe5c53a6-c2ea-11e7-8cad-0e8032b9f05a.png)

**Comment by SumithraKB** [comment]
@nevesseq  : can we style this email : 
![image](https://user-images.githubusercontent.com/26400070/32822838-671c0078-ca00-11e7-9c3e-95680f8335c5.png)
 Add a copy code button as well if possible.

**Comment by nevesseq** [comment]
@SumithraKB , copy code button cannot be added in email template

**Comment by SumithraKB** [comment]
ok. works.
