### ISSUE TITLE
Confirmation pop up issues on enable/disable of tool

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#61]
Go to summary page of an account  (eg : http://staging.obodos.com/account/summary/Tz9LvIEa)
click enabling a tool. The tool gets enabled before choosing "yes" or no" from the pop up. similarly while disabling the tool.

If user clicks close of the pop up,still the status of the tool gets changed.

![image](https://user-images.githubusercontent.com/26400070/32545155-cf39a760-c4a0-11e7-9648-85d2cb7d1e92.png)

**Comment by tanvisalkar** [comment]
The tool gets activated on switch turn on/off as a default functionality. have hidden the close button so a user will have to always select yes/no.

**Comment by SumithraKB** [comment]
ok that works.
