### ISSUE TITLE
times for display tool accept negative value

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#68]
http://staging.obodos.com/manage-tool/direct-booking-tool

![image](https://user-images.githubusercontent.com/17116943/32773705-0c0930b2-c950-11e7-8951-41308ce6ec81.png)

**Comment by cinthiavernekar** [comment]
Also to be fixed for page load
![image](https://user-images.githubusercontent.com/17116943/32773779-4b9535dc-c950-11e7-9cdd-267254db0acd.png)

**Comment by SumithraKB** [comment]
works now
![image](https://user-images.githubusercontent.com/26400070/32930562-7519d8e0-cb85-11e7-9eaf-4f4cce81e35e.png)
