### ISSUE TITLE
Create account : add asterisk for the required fields

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#8]
http://stage.projectx.com/website/create

current : no asterisk symbol for required fields 
![image](https://user-images.githubusercontent.com/17116943/31925417-239a5d9c-b8a6-11e7-9e98-fd60f30676d0.png)

**Comment by SumithraKB** [comment]
missing for "domain/website URL"
![image](https://user-images.githubusercontent.com/26400070/32048520-5f569086-ba67-11e7-9938-43d84d696c15.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/32049647-64c4b53a-ba6b-11e7-8130-582beae6af80.png)
