### ISSUE TITLE
list of accounts : select status pop up is not fully visible 

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#9]
http://stage.projectx.com/website

current : 
![image](https://user-images.githubusercontent.com/17116943/31925534-1a329a2a-b8a7-11e7-998f-4dbd6ab833d5.png)

**Comment by SumithraKB** [comment]
![image](https://user-images.githubusercontent.com/26400070/32049692-975ca750-ba6b-11e7-8735-83c6f737b8df.png)
