### ISSUE TITLE
Preview of left and right sticky not proper and error in console

### ISSUE THREAD

**Issue by SumithraKB** [ajency/ProjectX#91]
![image](https://user-images.githubusercontent.com/26400070/33057072-f15e83fc-ceae-11e7-93cc-646a53901213.png)

**Comment by SumithraKB** [comment]
Left sticky not proper.
Error is there in console
![image](https://user-images.githubusercontent.com/26400070/33112229-2e3066fa-cf78-11e7-87ab-c0abfe54ed33.png)

![image](https://user-images.githubusercontent.com/26400070/33112242-3dd7906a-cf78-11e7-9ff1-76f2e27b49cb.png)

**Comment by tanvisalkar** [comment]
console errors are fixed but re the font issue of the button it wont match always as the external website will have its own stylesheet.

**Comment by SumithraKB** [comment]
Works now
