### ISSUE TITLE
pop up issue in below scenario

### ISSUE THREAD

**Issue by cinthiavernekar** [ajency/ProjectX#98]
http://cloudpath.ajency.in/

Configuration selected : 
![image](https://user-images.githubusercontent.com/17116943/33160295-13557b58-d041-11e7-84bf-f544ea1d7e29.png)
![image](https://user-images.githubusercontent.com/17116943/33160301-1f35babe-d041-11e7-9de2-8de1c0cae63f.png)

Current : pop up is displayed on all the pages though specific page(team page) is selected.
![image](https://user-images.githubusercontent.com/17116943/33160318-59f648da-d041-11e7-9a2f-489520081795.png)

**Comment by cinthiavernekar** [comment]
to be fixed for mobile as well

**Comment by cinthiavernekar** [comment]
works

**Comment by SumithraKB** [comment]
Still coming on all pages : 
![image](https://user-images.githubusercontent.com/26400070/33358069-652bbb54-d4ec-11e7-9575-aa7797ee8383.png)

![image](https://user-images.githubusercontent.com/26400070/33358077-6fd54052-d4ec-11e7-87fb-3a97a09d7b14.png)

**Comment by cinthiavernekar** [comment]
fixed
